name: monitor blog

on:
  schedule:
    - cron: "*/15 * * * *"

  push:
    branches: [master]

  issues:
    types:
      - "opened"

  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - run: go run monitor.go